### PR TITLE
bundle update

### PR DESCRIPTION
**Pull request by dorianmariecom**

### CODE REVIEW

**Comment by fractaledmind** [comment]
Seems we have a build problem:
```
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:456:in
`parse_stream': undefined method `parse' for #<Psych::Parser:0x000055e33ea5f830
@handler=#<Psych::Handlers::DocumentStream:0x000055e33ea5fd08 @stack=[],
@last=nil, @root=nil, @start_line=nil, @start_column=nil, @end_line=nil,
@end_column=nil, @block=#<Proc:0x000055e33ea5f970
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:390>>,
@external_encoding=0> (NoMethodError)
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:390:in `parse'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:280:in `load'
from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:582:in `block
in load_file'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:581:in `open'
from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/psych.rb:581:in
`load_file'
	from extconf.rb:162:in `mini_portile_config'
	from extconf.rb:157:in `sqlite3_config'
	from extconf.rb:141:in `minimal_recipe'
	from extconf.rb:51:in `configure_packaged_libraries'
	from extconf.rb:17:in `configure'
	from extconf.rb:285:in `<main>'
```

Can't merge until we figure out how to resolve this.

**Comment by dorianmariecom** [comment]
Looks like it's a bundler issue, upgrading bundler should fix it

**Comment by dorianmariecom** [comment]
Hmmm, it wasn't bundler, maybe because it's an old ruby version?

**Comment by dorianmariecom** [comment]
See https://github.com/mikel/mail/pull/1597 for the warnings

**Pull request merged**
